kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-wcni
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  podSubnet: "10.240.0.0/16"
  serviceSubnet: "10.0.0.0/16"
  # kubeProxyMode: "ipvs"
nodes:
  - role: control-plane
    image: kindest/node:v1.31.4
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true,node=master"
        ---
        kind: ClusterConfiguration
        apiServer:
            extraArgs:
              enable-admission-plugins: NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook    
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        # listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        # listenAddress: "127.0.0.1"
      #   protocol: TCP
      # - containerPort: 30002
      #   hostPort: 15021
        # listenAddress: "127.0.0.1"
      #   protocol: TCP
      # - containerPort: 30003
      #   hostPort: 15023
        # listenAddress: "127.0.0.1"
      #   protocol: TCP
      # - containerPort: 30004
      #   hostPort: 15024
        # listenAddress: "127.0.0.1"
      #   protocol: TCP
      # - containerPort: 30005
      #   hostPort: 15025
        # listenAddress: "127.0.0.1"
      #   protocol: TCP
      # - containerPort: 31000
      #   hostPort: 3000
        # listenAddress: "127.0.0.1"
      #   protocol: TCP
      # - containerPort: 31100
      #   hostPort: 3100
        # listenAddress: "127.0.0.1"
      #   protocol: TCP
      # - containerPort: 31200
      #   hostPort: 3200
        # listenAddress: "127.0.0.1"
      #   protocol: TCP
      # - containerPort: 31300
      #   hostPort: 3300
        # listenAddress: "127.0.0.1"
      #   protocol: TCP
      # - containerPort: 31400
      #   hostPort: 3400
        # listenAddress: "127.0.0.1"
      #   protocol: TCP
      # - containerPort: 31500
      #   hostPort: 3500
        # listenAddress: "127.0.0.1"
  #       protocol: TCP
  # - role: worker
  #   image: kindest/node:v1.31.4
  # - role: worker
  #   image: kindest/node:v1.31.4
