# apiVersion: v1
# kind: Namespace
# metadata:
#   labels:
#     app.kubernetes.io/instance: ingress-nginx
#     app.kubernetes.io/name: ingress-nginx
#   name: ingress-nginx
# ---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mytest-project-nginx
  namespace: istio-system
spec:
  dnsNames:
  - 'nginx-ingress-nginx-controller'
  - '*.kind.local'
  - '*.kind.int.local'
  - '*.kind.ext.local'
  issuerRef:
    name: issuer-selfsigned-nginx
  secretName: mytest-project-tls-ext-nginx
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer-selfsigned-nginx
  namespace: istio-system
spec:
  selfSigned: {}