apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mytest-project
  namespace: istio-system
spec:
  dnsNames:
  - '*.kind.ext.local'
  - '*.kind.local'
  - '*.kind.int.local'
  - 'istio-ingressgateway'
  - 'istio-ingressgateway.istio-system.svc.cluster.local'
  - 'istio-ingressgateway-internal'
  - 'istio-ingressgateway-internal.istio-system.svc.cluster.local'
  issuerRef:
    name: issuer-selfsigned-istio
  secretName: mytest-project-tls-int-istio
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer-selfsigned-istio
  namespace: istio-system
spec:
  selfSigned: {}